# syntax=docker/dockerfile:1

ARG NODE_VERSION=20

FROM node:${NODE_VERSION}

# Use development node environment by default.
ENV NODE_ENV development

WORKDIR /usr/src/app

# Download dependencies as a separate step to take advantage of Docker's caching.
# Leverage a cache mount to /root/.npm to speed up subsequent builds.
# Leverage a bind mounts to package.json and package-lock.json to avoid having to copy them into
# into this layer.
RUN npm i -g @angular/cli

# Copy package.json and package-lock.json and install dependencies.
COPY package*.json ./

RUN npm ci

# Run the application as a non-root user.
USER node

# Expose the port that the application listens on.
EXPOSE 4200

# Run the application.
CMD npm run start
