import {SegmentModel} from "../models/segment.model";

export const SEGMENTS: SegmentModel[] = [
  {
    id: 1,
    title: 'Restaurantes Comerciais e Fast Foods',
    subtitle: 'Subtitle',
    content: 'Oferecemos soluções customizadas para o tamanho de seu negócio. Linha completa de produtos, equipamentos e material de apoio para garantir o mais elevado padrão de higiene para seu estabelecimento.',
    image: '/assets/restaurante-fast-foods.jpg',
    color: 'bg-orange-500',
  },
  {
    id: 2,
    title: 'Concessionária de Alimentação',
    subtitle: 'Subtitle',
    content: 'Oferecemos uma linha completa de produtos, equipamentos e material de apoio que garantem o melhor resultado ao menor custo possível.',
    image: '/assets/concessionaria-de-comidas.jpg',
    color: 'bg-green-400',
  },
  {
    id: 3,
    title: 'Hotéis e Pousadas',
    subtitle: 'Subtitle',
    content: 'Oferecemos soluções customizadas para limpeza e higienização de todas as áreas de seu estabelecimento.',
    image: '/assets/hoteis.jpg',
    color: 'bg-teal-500',
  },
  {
    id: 4,
    title: 'Hospitais, Clinicas e Laboratórios',
    subtitle: 'Subtitle',
    content: 'Oferecemos soluções customizadas para as mais rigorosas exigências de Higiene e limpeza em um ambiente hospitalar.',
    image: '/assets/hospitais.jpg',
    color: 'bg-emerald-500',
  },
  {
    id: 5,
    title: 'Escolas',
    subtitle: 'Subtitle',
    content: 'Oferecemos produtos e equipamentos de alta performance para assegurar o mais alto padrão de limpeza e higienização de seu estabelecimento.',
    image: '/assets/escolas.jpg',
    color: 'bg-red-500',
  },
  {
    id: 6,
    title: 'Indústrias',
    subtitle: 'Subtitle',
    content: 'Oferecemos uma linha completa de produtos de alta performance customizada para o seu tamanho e tipo de indústria. ',
    image: '/assets/industrias.jpg',
    color: 'bg-yellow-500',
  },
  {
    id: 7,
    title: 'Supermercados',
    subtitle: 'Subtitle',
    content: 'Oferecemos um programa de Higiene e Limpeza customizado que garante o mais alto padrão de higiene e limpeza para seu estabelecimento.',
    image: '/assets/supermercados.jpg',
    color: 'bg-lime-500',
  },
  {
    id: 8,
    title: 'Clubes e Academias',
    subtitle: 'Subtitle',
    content: 'Oferecemos produtos e equipamentos de alta performance que garantem a correta limpeza e higienização com foco na otimização de custos.',
    image: '/assets/academias.jpg',
    color: 'bg-purple-500',
  },
  {
    id: 9,
    title: 'Edifícios Comerciais',
    subtitle: 'Subtitle',
    content: 'Oferecemos uma linha completa de produtos, equipamentos e dispensers para garantir um ambiente limpo e higienizado para seus colaboradores e clientes que visam a otimização de custos.',
    image: '/assets/edificios-comerciais.jpg',
    color: 'bg-red-500',
  }
];
